services:
  # Backend API Service
  - type: web
    name: shoq-backend
    runtime: node
    plan: starter
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: MONGO_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPERATOR_ID
        sync: false
      - key: OPERATOR_KEY
        sync: false
      - key: HEDERA_USDC_TOKEN_ID
        sync: false
      - key: SHOP_OWNER_ADDRESS
        sync: false
      - key: EMAIL_USERNAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: FRONTEND_URL
        value: https://shoq-frontend.onrender.com
      - key: FULFILLMENT_EMAIL
        value: orders@shoq.me

  # Frontend Web Service
  - type: web
    name: shoq-frontend
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_API_URL
        value: https://shoq-backend.onrender.com
